version: "3"

services:
  links_retriever:
    build: "./links_retriever/app/"
    depends_on:
      - scorer
    ports:
      - "8080:8080"
    environment: 
      - MONGODB_CONNECTION_URL=mongodb://factmata:factmata@aspronedario.com/factmata_interview
      - RETRIEVER_THREADPOOL_SIZE=${RETRIEVER_THREADPOOL_SIZE}
    links:
      - "nginx:loadbalancer"
    #ulimits:
      #nproc: 65535
      #nofile:
        #soft: 20000
        #hard: 40000

  scorer:
    build: "./scorer/app/"
    environment:
      - SCORER_THREADPOOL_SIZE=${SCORER_THREADPOOL_SIZE}
    expose:
      - "8025"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - scorer
    expose:
      - "8024"